# Broadcasting in Python

- row 1: carbs
- row 2: protein
- row 3: fat
- column 1: apples
- column 2: beef
- column 3: eggs
- column 4: potatoes

In [28]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


Number of calories per row:

In [29]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


Porcentagem de calorias por coluna:

In [30]:
percentage = 100*A/cal.reshape(1, 4) # broadcasting 
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


Reshape - an example of Python broadcasting where you take a matrix A (3x4) and divide it by (1x4) matrix. Command reshape is not actualy needed, cal is already (1x4).

If you a using Python matrices and you're not quite sure the dimensions of the matrix, you can call the reshape command just to make sure, the cost is very low.

Suppose img is a (32,32,3) array, representing a 32x32 image with 3 color channels red, green and blue. How do you reshape this into a column vector?

In [31]:
img = np.random.randn(32, 32, 3)
x = img.reshape(32*32*3, 1)
print(img)
print(x)

[[[-0.71923583  0.15349492  1.87243323]
  [ 0.11188588 -0.22357783 -0.16984956]
  [-0.3591245  -0.08067499 -0.76119448]
  ...
  [ 0.15475632 -0.66979333  0.41805871]
  [ 0.65567845  0.2540736   0.46782401]
  [-1.61132892 -1.23933449 -1.09043136]]

 [[-0.55234702 -2.08790222 -0.39264267]
  [ 1.36881741 -1.42701271 -1.57868982]
  [-0.53769402  0.45031573  0.24709644]
  ...
  [-0.02303319  0.67422538 -0.1793131 ]
  [ 0.3646837  -2.19347837 -1.97547216]
  [ 0.36342695  0.47599507  0.83096549]]

 [[-1.25516445 -1.11016717  1.84384451]
  [ 0.10053026 -0.88714292 -0.45713427]
  [ 0.45608219  1.80472597 -1.4124258 ]
  ...
  [-0.82007548 -1.207692   -0.77996581]
  [ 0.59678068 -0.9181804  -1.04861312]
  [ 0.80850279  1.36612446 -0.69326416]]

 ...

 [[-0.43112878 -1.05494622 -0.13392678]
  [-1.06328053 -2.52033623  0.45099696]
  [ 0.61083232 -1.08132487  1.25340171]
  ...
  [ 0.99316821 -0.36729682 -1.42806953]
  [-1.21785707 -1.66703795 -0.75001961]
  [-0.17166259 -0.39346843  0.8207928 ]]

 [

Shape:

In [32]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


Shape: 

In [33]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

Recall that "np.dot(a,b)" performs a matrix multiplication on a and b, whereas "a*b" performs an element-wise multiplication.

In [34]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


Vectorization:

In [38]:
# a.shape = (3,4)
# b.shape = (4,1)
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
d = np.random.randn(3, 4)

for i in range(3):
  for j in range(4):
    d[i][j] = a[i][j] + b[j]
print(d)
print(d.shape)

[[ 1.53144439  1.18194877 -2.54920313  0.81245935]
 [ 1.00526434  0.30543077  0.2851037  -0.99906665]
 [ 0.75689621  1.45849249 -1.73933409 -0.3889218 ]]
(3, 4)


In [39]:
c = a + b.T # T = transposed
print(c)
print(c.shape)

[[ 1.53144439  1.18194877 -2.54920313  0.81245935]
 [ 1.00526434  0.30543077  0.2851037  -0.99906665]
 [ 0.75689621  1.45849249 -1.73933409 -0.3889218 ]]
(3, 4)


What the following do? (broadcasting)

In [40]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
print(c.shape)

[[ 2.35220568  0.20809817  0.20156893]
 [-0.8315542  -0.32233993 -0.19244965]
 [ 0.14289634 -0.13589182 -0.46404304]]
(3, 3)
