In [18]:
import numpy as np

a = np.random.randn(5)
print(a)

[-0.17507627  1.05748401 -1.48041553 -0.28747192 -0.15778371]


In [19]:
print(a.shape)

(5,)


(5, ) is a rank 1 array. It is a data structure, but it doens't behave consistently as either a row nor a column vector. Avoid using this array.

In [12]:
print(a.T) # transposed

[[-0.41928744  0.8563145  -0.05120945 -1.2113937  -0.47318429]]


In [13]:
print(np.dot(a, a.T))

[[ 0.17580195 -0.35904191  0.02147148  0.50792216  0.19840023]
 [-0.35904191  0.73327452 -0.0438514  -1.03733399 -0.40519457]
 [ 0.02147148 -0.0438514   0.00262241  0.06203481  0.02423151]
 [ 0.50792216 -1.03733399  0.06203481  1.46747469  0.57321247]
 [ 0.19840023 -0.40519457  0.02423151  0.57321247  0.22390337]]


We should get a matrix, not a number! We should avoid notations like (5,) and explicitly determine (5, 1).

In [16]:
b = np.random.randn(5, 1) # make it explicit
print(b)

[[ 1.63760686]
 [-0.65389043]
 [ 0.25735439]
 [-0.41745906]
 [-0.77787665]]


In [17]:
print(b.T)

[[ 1.63760686 -0.65389043  0.25735439 -0.41745906 -0.77787665]]


Difference: above we got 2 [[]]!

In [8]:
print(np.dot(b, b.T))

[[ 0.17580195 -0.35904191  0.02147148  0.50792216  0.19840023]
 [-0.35904191  0.73327452 -0.0438514  -1.03733399 -0.40519457]
 [ 0.02147148 -0.0438514   0.00262241  0.06203481  0.02423151]
 [ 0.50792216 -1.03733399  0.06203481  1.46747469  0.57321247]
 [ 0.19840023 -0.40519457  0.02423151  0.57321247  0.22390337]]


In [26]:
assert(b.shape == (5, 1))

We can throw assertion statement like this to make sure this is a (5, 1) vector.
These assertions are really inexpensive to execute, and are also good for documentation.