In [2]:
import numpy as np 

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


### Vectorization

Vectorized:

In [3]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + " ms")

250779.84902276332
Vectorized version: 1.8677711486816406 ms


Non-vectorized (for loop):

In [4]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop: " + str(1000*(toc-tic)) + " ms")

250779.84902276171
For loop: 685.6722831726074 ms


### More Vectorization Examples

Say you need to apply the exponential operation on every element of a matrix/vector. v = [v1 ... v2]

In [9]:
v = np.random.rand(4)
u = np.exp(v) # np.abs(v), np.maximum(v,0)

print(v)
print(u)

[0.65927682 0.79647092 0.38222268 0.38585841]
[1.93339364 2.21770065 1.4655384  1.47087639]
